baseurl = "/"
languageCode = "en-us"
title = "Alex K Gold Blog"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Alex K Gold"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/akgold"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/alexkgold"

[params]
    description = "Blogging about data science, occasionally Star Wars."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "akg_profile.jpg"
    width = 50
    height = 50
    alt = "It Me"

