---
title: "Recent Speaking"
---

```{r setup, include = FALSE, message = FALSE, warning = FALSE}
library(dplyr)
library(magrittr)

make_link <- function(text, link) {
  glue::glue("<a href={link}>{text}</a>")
}
```

```{r, echo = FALSE}
bind_cols(
  tibble::tribble(
    ~Date,            ~Title,         ~Slides,             ~Code, 
    "2020-03-28", "DC SatRDays: Break Up Shiny Apps", "https://docs.google.com/presentation/d/1PJT0LfTAMz_6GCyLxMnPDAWqKmzWJKCOfcXosH-jEVk/edit?usp=sharing", "github.com/akgold/shiny_break_up_satrday",
    "2020-07-28", "RStudio Webinar: Growing a Remote Data Science Team", "https://docs.google.com/presentation/d/15rHvguWGVQ6elrw9G2CnJOasKvBS1TliEEDA931ZSVs/edit?usp=sharing", NA,
    "2020-06-17", "e-RUM: Design Patterns for Big Shiny Apps", "https://docs.google.com/presentation/d/1mAAU0sw7GIVwOeGVsvdZCWA86mHhu-GZgkjYgreqmBk/edit", "https://github.com/akgold/erum-big-shiny",
    "2020-12-03", "DCR: Powerful Package Patterns", "https://docs.google.com/presentation/d/1eJFTvWB1svlSdUsv_-3h2-665VnCMz8Cya7MlOjTnwQ/edit?usp=sharing", NA,
    "2019-05-21", "Data Scientists Doing Software Engineering", "https://speakerdeck.com/akgold/2019-05-21-data-scientists-and-software-engineering", NA,
    "2019-06-12", "Big Data Toronto 2019: Big Data and R, Spark", "https://speakerdeck.com/akgold/2019-06-12-big-data-toronto-spark", "https://github.com/akgold/big_data_2019",
    "2019-09-17", "DC Data Science Meetup: Love for Linear Models", "https://speakerdeck.com/akgold/love-for-linear-models", NA,
    "2019-09-17", "Webinar: Reproducible Data Science", "https://speakerdeck.com/akgold/2019-09-17-creating-reproducible-data-science", "https://github.com/akgold/2019-09-17_john_deere_webinar", 
    "2019-11-14", "Big Data London 2019: Big Data and R: Databases", "https://speakerdeck.com/akgold/r-and-big-data-databases", 
    "https://github.com/akgold/bdl_2019", 
    "2020-01-03", "RStudio::conf(2020): Deploying End-to-End Data Science with Shiny, Plumber, and Pins", "https://github.com/akgold/rsconf2020-deployment/blob/master/RStudio%20Conf%202020%20Talk.pdf", "https://github.com/akgold/rsconf2020-deployment",
    "2021-02-17", "RStudio Webinar: Managing Packages for Open Source Data Science", NA, NA,
    "2021-07-07", "UseR 2021: Reliably Reproducible Product Packages", "https://docs.google.com/presentation/d/1a7YvEsknIcOAUJGskjW-jooW-A4ochg12k7iS5WpwAs/edit?usp=sharing", NA,
    "2021-12-09", "DCR: Reliably Reproducible R-Tifacts", "https://docs.google.com/presentation/d/1NvL11GwM_B17BfFf8Xhg8VNT0cQx9Kzpy5_C3MJ6zo0/edit?usp=sharing", NA
  ), 
  tibble::tribble(
    ~Video, 
    NA,
    "https://rstudio.com/resources/webinars/enabling-remote-data-science-teams/",
    "https://youtu.be/NwVOvfpGq4o",
    NA,
    NA, 
    NA, 
    NA, 
    NA, 
    "https://www.youtube.com/watch?v=GQcEnlz3jrI", 
    "https://rstudio.com/resources/rstudioconf-2020/deploying-end-to-end-data-science-with-shiny-plumber-and-pins/", 
    "https://rstudio.com/resources/webinars/managing-packages-for-open-source-data-science/", 
    NA, 
    "https://youtu.be/-6TlzhRA9vA"
  )
) %>%
  dplyr::transmute(
    Date,
    Title = make_link(Title, Slides),
    Code = ifelse(is.na(Code), NA, make_link("Code", Code)), 
    Video = ifelse(is.na(Video), NA, make_link("Video", Video))
  ) %>%
  dplyr::arrange(desc(Date)) %>%
  reactable::reactable(
    defaultPageSize = 50,
    list(
      Date = reactable::colDef(
        minWidth = 25
      ),
      Title = reactable::colDef(
        html = TRUE
      ), 
      Code = reactable::colDef(
        html = TRUE, 
        maxWidth = 60
      ), 
      Video = reactable::colDef(
        html = TRUE, 
        maxWidth = 65
      )
    )
  )
```

Selected slides are available at [speakerdeck](https://speakerdeck.com/akgold).

Generally, my presentations involve demoing R code, which is available on [GitHub](https://github.com/akgold/).
