on:
  push:
    branches:
      - main

jobs:
  build-site:
    name: build-site
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/install-quarto@v1
      - run: |
          quarto --version
      - name: "Quarto render"
        shell: bash
        run: |
          quarto render --execute-debug
      - uses: actions/upload-artifact@v2
        with:
          name: _site
          path: _site

  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: build-site
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: _site # optional
         # Destination path
         path: _site # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@master
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
          email: alexkgold@gmail.com
          build_dir: _site/ # defaults to _site
